# Generated by Django 4.2.3 on 2023-07-22 18:19

import core.models
from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('raca', models.CharField(max_length=50, verbose_name='Raça')),
                ('imagem', stdimage.models.StdImageField(force_min_size=False, null=True, upload_to=core.models.get_file_path, variations={}, verbose_name='Imagem')),
            ],
        ),
    ]
